#spring:
#  application:
#    name: course
#
#  server:
#    port: 8082
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ead-course
#    username: postgres
#    password: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob:
#          non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
#  output:
#    ansi:
#      enabled: Always
#
#  logging:
#    level:
#      root: INFO
#      com.ead: TRACE
#      org.hibernate.SQL: DEBUG
#      org.springframework.web: DEBUG
#      org.hibernate: INFO
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
